### PR TITLE
[Docker] Resolves #11 : avoid hardcoded credentials

### LINKED ISSUE #11: Use user specified superuser configuration for docker
Use user-specified username, password, and email for the Django project in the docker file.

### PR DESCRIPTION
**Pull request by yannis-mlgrn**
Fixes #11 

# Related Issues :
 - #11 
# Proposed Changes:

Add arguments to docker file for allow to a user to specify his super user credentials before build and avoid to have these information hardcoded

# Features : 

- ✨ Added build arguments in `dockerfile`
- ⚡️ Improve documentation

### CODE REVIEW

**Comment by yannis-mlgrn** [comment]
@dmdhrumilmistry, I can't launch your `docker-compose` with this command : `docker-compose up`. I've this error, it's nomal ? idk if we should create a issue about this
```
ERROR: The Compose file is invalid because:
Service web has neither an image nor a build context specified. At least one must be provided.
```

**Comment by dmdhrumilmistry** [comment]
> @dmdhrumilmistry, I can't launch your `docker-compose` with this command : `docker-compose up`. I've this error, it's nomal ? idk if we should create a issue about this
> 
> ```
> ERROR: The Compose file is invalid because:
> Service web has neither an image nor a build context specified. At least one must be provided.
> ```

No, docker-compose should work. But It seems like there might be a small bug introduced due to a typo in the [docker-compose](https://github.com/dmdhrumilmistry/GooglePhish/blob/60b2138aca8e308704e39116fa1a88316e648b12/docker-compose.yml#L6) file, build tag should have value `Dockerfile` instead of `dockerfile`. I'll fix it.

**Comment by yannis-mlgrn** [comment]
hey @dmdhrumilmistry ! 
I can't login to dashboard with your docker-compose, the credentials specify in them doesn't working 
Do you have an idea why ?
I've used the last version of the repo with not my modifications in Dockerfile

**Comment by dmdhrumilmistry** [comment]
> hey @dmdhrumilmistry ! I can't login to dashboard with your docker-compose, the credentials specify in them doesn't working Do you have an idea why ? I've used the last version of the repo with not my modifications in Dockerfile

That's weird, I tried it on my machine and it was working. I'll retest it again, and update you soon.

**Review by dmdhrumilmistry — CHANGES_REQUESTED** [review]
@yannis-mlgrn can you provide default values to build args that were being used in Dockerfile; in case the user doesn't provide build args then GitHub `docker build and push` workflow will break and also change README dj_email to `admin@localhost.local` to avoid using any company's or private email in it.

**Review by dmdhrumilmistry — APPROVED** [review]

**Pull request merged**
